# This sweep contains the training configuration of all the RGB flow models 
# trained on a colorful image of size [3 x 32 x 32]
# This contains the Glow models and the Neural Spline Flows

project: training-dgms
entity: dgm-l6
count: 10000

# Change the name of the run to [flow_type]_[dataset_type]_[previous_run_name]
run_name_changer:
  expression: |
    from meta_configurations import get_coupling 

    def func(conf, run_name):
      coupling_type = get_coupling(conf)
      return f"{coupling_type}_{conf['data']['dataset']}_{run_name}"
  function_of_interest: func
