base_model:
  run_dir: runs/flow_fmnist
  config_dir: experiments/training/flow_elaborate_fmnist.yaml
  checkpoint_dir: runs/flow_fmnist/checkpoints/de_nf_latest.pt
data:
  # override the dataloader args that is obtained from the run_dir
  in_distribution:
    dataloader_args:
      dataset: fashion-mnist
  out_of_distribution:
    dataloader_args:
      dataset: fashion-mnist
  # for reproducibility
  seed: 10
ood:
  pick_single: True
  seed: 10
  method: ood.methods.local_optimization.OODLocalOptimization
  method_args:
    optimization_steps: 1000
    optimizer: torch.optim.SGD
    optimizer_args:
      lr: 0.0001
    optimization_objective: nll
    intermediate_image_log_frequency: 1
    progress_bar: True
    representation_rank: 2

logger:
  project: ood-detection-single-runs
  entity: dgm-l6
